### ISSUE TITLE
Table1: "Suspended" instead of "Held"

### ISSUE THREAD

**Issue by odungern** [hsu-aut/IndustrialStandard-ODP-ISA88#11]
In Table 1, line 2 the answer should be "Machine 'X' went from 'Execute' to 'Held' due to an internal issue - OR Machine 'X' went from 'Execute' to **'Suspended'** due to an external issue", shouldn't it?

**Comment by odungern** [comment]
.. this is a minor issue and perhaps it serves to test the reader's concentration ;-).

I really think that your ontologies are of high quality and a great help to practitioners wishing to get more formal precision in systems engineering. Many thanks!

**Comment by aljoshakoecher** [comment]
Thank you very much for raising this issue. Nice catch, that was really a test for PackML experts. I actually had to read this issue twice to understand the problem ^^
Should be fixed by [4f04e68](https://github.com/hsu-aut/IndustrialStandard-ODP-PackML/commit/4f04e683310e639f24256be15af31259fd7c8622).

PS: The bigger question to me was: Why was this table inserted as an image 🤔. I changed that to a proper table.
